import 'package:flutter/material.dart';

@immutable
class StringConstants {
  const StringConstants._();
  static const String appName = "Telemedicine";
  static const String signUp = "Sign Up";
  static const String signIn = "Sign In";
  static const String createAcc = "Create Account";
  static const String alreadyHave = "Already have an account?";
  static const String dontHave = "Don't have an account?";
  static const String username = "Username";
  static const String email = "Email";
  static const String phone = "Phone";
  static const String password = "Password";
  static const String buAlanBos = "Bu alan boş geçilemez";
  static const String forgotPassword = "Forgot your Password?";
  static const String home = "Home";
  static const String doctors = "Doctors";
  static const String notification = "Notifications";
  static const String menu = "Menu";
  static const String findYour = "Find Your";
  static const String specialist = "Specialist";
  static const String categories = "Categories";
  static const String seeAll = "See All";
  static const String availableDoctor = "Available Doctor";
  static const String available = "Available";
  static const String experience = "Experience";
  static const String patients = "Patients";
  static const String review = "Review";
  static const String bookAn = "Book an Appoinment";
  static const String appointment = "Appointment";
  static const String confirmAppointment = "Confirm Appointment";
  static const String appointmentDate = "Appointment Date";
  static const String appointmentTime = "Appointment Time";
  static const String myAppointment = "My Appointment";
  static const String profile = "Profile";
  static const String settings = "Settings";
  static const String logOut = "Log Out";
  static const String edit = "Edit";
  static const String name = "Name";
  static const String phoneNumber = "Phone Number";
  static const String address = "Address";
  static const String upcoming = "Upcoming";
  static const String past = "Past";
  static const String date = "Date";
  static const String time = "Time";
  static const String doctor = "Doctor";
  static const String appointmentType = "Appointment Type";
  static const String place = "Place";
  static const String cancel = "Cancel";
  static const String reschedule = "Reschedule";
}
